const countryData = [
    { code: 'US', name: 'United States', dialCode: '+1', flag: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg' },
    { code: 'AR', name: 'Argentina', dialCode: '+54', flag: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg' },
    { code: 'BR', name: 'Brazil', dialCode: '+55', flag: 'https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg' },
    { code: 'CA', name: 'Canada', dialCode: '+1', flag: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Canada.svg' },
    { code: 'CL', name: 'Chile', dialCode: '+56', flag: 'https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg' },
    { code: 'CN', name: 'China', dialCode: '+86', flag: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_China.svg' },
    { code: 'CO', name: 'Colombia', dialCode: '+57', flag: 'https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg' },
    { code: 'FR', name: 'France', dialCode: '+33', flag: 'https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg' },
    { code: 'DE', name: 'Germany', dialCode: '+49', flag: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg' },
    { code: 'IN', name: 'India', dialCode: '+91', flag: 'https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg' },
    { code: 'IT', name: 'Italy', dialCode: '+39', flag: 'https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg' },
    { code: 'JP', name: 'Japan', dialCode: '+81', flag: 'https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg' },
    { code: 'MX', name: 'Mexico', dialCode: '+52', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg' },
    { code: 'RU', name: 'Russia', dialCode: '+7', flag: 'https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg' },
    { code: 'ES', name: 'Spain', dialCode: '+34', flag: 'https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg' },
    { code: 'ZA', name: 'South Africa', dialCode: '+27', flag: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg' },
    { code: 'GB', name: 'United Kingdom', dialCode: '+44', flag: 'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg' },
    { code: 'AU', name: 'Australia', dialCode: '+61', flag: 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Australia.svg' },
    { code: 'NZ', name: 'New Zealand', dialCode: '+64', flag: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg' },
    { code: 'IE', name: 'Ireland', dialCode: '+353', flag: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg' },
    { code: 'SG', name: 'Singapore', dialCode: '+65', flag: 'https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg' },
    { code: 'KR', name: 'South Korea', dialCode: '+82', flag: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg' },
    { code: 'HK', name: 'Hong Kong', dialCode: '+852', flag: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Hong_Kong.svg' },
    { code: 'TW', name: 'Taiwan', dialCode: '+886', flag: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg' },
    { code: 'TH', name: 'Thailand', dialCode: '+66', flag: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg' },
    { code: 'MY', name: 'Malaysia', dialCode: '+60', flag: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg' },
    { code: 'PH', name: 'Philippines', dialCode: '+63', flag: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg' },
    { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: 'https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg' },
    { code: 'ID', name: 'Indonesia', dialCode: '+62', flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg' },
    { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: 'https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg' },
    { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg' },
    { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg' },
    { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', flag: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg' },
    { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', flag: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg' },
    { code: 'IL', name: 'Israel', dialCode: '+972', flag: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg' },
    { code: 'EG', name: 'Egypt', dialCode: '+20', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg' },
    { code: 'NG', name: 'Nigeria', dialCode: '+234', flag: 'https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg' },
    { code: 'KE', name: 'Kenya', dialCode: '+254', flag: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg' },
    { code: 'GH', name: 'Ghana', dialCode: '+233', flag: 'https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg' },
    { code: 'UG', name: 'Uganda', dialCode: '+256', flag: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg' },
    { code: 'TZ', name: 'Tanzania', dialCode: '+255', flag: 'https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg' },
    { code: 'ZM', name: 'Zambia', dialCode: '+260', flag: 'https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg' },
    { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg' },
    { code: 'ET', name: 'Ethiopia', dialCode: '+251', flag: 'https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg' },
    { code: 'SN', name: 'Senegal', dialCode: '+221', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg' },
    { code: 'CI', name: 'Ivory Coast', dialCode: '+225', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Cote_d%27Ivoire.svg' },
    { code: 'UG', name: 'Uganda', dialCode: '+256', flag: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg' },
    { code: 'CM', name: 'Cameroon', dialCode: '+237', flag: 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg' },
    { code: 'DZ', name: 'Algeria', dialCode: '+213', flag: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg' },
    { code: 'MA', name: 'Morocco', dialCode: '+212', flag: 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg' },
    { code: 'TN', name: 'Tunisia', dialCode: '+216', flag: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg' },
    { code: 'GR', name: 'Greece', dialCode: '+30', flag: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg' },
    { code: 'PT', name: 'Portugal', dialCode: '+351', flag: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg' },
    { code: 'NL', name: 'Netherlands', dialCode: '+31', flag: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg' },
    { code: 'BE', name: 'Belgium', dialCode: '+32', flag: 'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg' },
    { code: 'CH', name: 'Switzerland', dialCode: '+41', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg' },
    { code: 'AT', name: 'Austria', dialCode: '+43', flag: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg' },
    { code: 'SE', name: 'Sweden', dialCode: '+46', flag: 'https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg' },
    { code: 'NO', name: 'Norway', dialCode: '+47', flag: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg' },
    { code: 'FI', name: 'Finland', dialCode: '+358', flag: 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg' },
    { code: 'DK', name: 'Denmark', dialCode: '+45', flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg' },
  ];
  
  export default countryData;